import React from 'react';
import { AiProfileAnalysis } from '../types';
import { Sparkles, Loader2, RefreshCw, Brain, Lightbulb, Award, TrendingUp, Target } from 'lucide-react';

interface AiProfileAnalysisProps {
  analysis: AiProfileAnalysis | null;
  isLoading: boolean;
  onGenerate: () => void;
}

export const AiProfileAnalysis: React.FC<AiProfileAnalysisProps> = ({
  analysis,
  isLoading,
  onGenerate,
}) => {
  if (!analysis && !isLoading) {
    return (
      <div className="glass rounded-2xl p-6 border border-slate-800/60 animate-slide-up">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2 rounded-lg bg-purple-950/50 border border-purple-800/60">
            <Sparkles className="w-5 h-5 text-purple-400" />
          </div>
          <div>
            <h3 className="font-bold text-lg text-white">AI Intelligence Briefing</h3>
            <p className="text-xs text-slate-400">Gemini-powered developer portfolio analysis</p>
          </div>
        </div>
        <p className="text-slate-400 mb-4">
          Generate a comprehensive AI analysis of this developer's portfolio including archetype classification,
          technical strengths, signature innovations, and collaboration suggestions.
        </p>
        <button
          onClick={onGenerate}
          disabled={isLoading}
          className="btn-primary"
        >
          <Sparkles className="w-4 h-4" />
          Generate AI Briefing
        </button>
      </div>
    );
  }

  if (isLoading) {
    return (
      <div className="glass rounded-2xl p-6 border border-slate-800/60 animate-slide-up">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2 rounded-lg bg-purple-950/50 border border-purple-800/60">
            <Loader2 className="w-5 h-5 text-purple-400 animate-spin" />
          </div>
          <div>
            <h3 className="font-bold text-lg text-white">Analyzing Portfolio...</h3>
            <p className="text-xs text-slate-400">Gemini is synthesizing developer intelligence</p>
          </div>
        </div>
        <div className="space-y-3">
          <div className="h-4 bg-slate-800 rounded animate-pulse" style={{ width: '60%' }} />
          <div className="h-4 bg-slate-800 rounded animate-pulse" style={{ width: '80%' }} />
          <div className="h-4 bg-slate-800 rounded animate-pulse" style={{ width: '40%' }} />
        </div>
      </div>
    );
  }

  return (
    <div className="glass rounded-2xl p-6 border border-purple-500/30 animate-slide-up">
      <div className="flex items-center gap-3 mb-6">
        <div className="p-2 rounded-lg bg-purple-950/50 border border-purple-800/60">
          <Sparkles className="w-5 h-5 text-purple-400" />
        </div>
        <div>
          <h3 className="font-bold text-lg text-white">AI Intelligence Briefing</h3>
          <p className="text-xs text-slate-400">Generated by Gemini 3.6 Flash</p>
        </div>
        <button
          onClick={onGenerate}
          className="ml-auto btn-ghost text-xs"
        >
          <RefreshCw className="w-3.5 h-3.5" />
          Regenerate
        </button>
      </div>

      <div className="space-y-6">
        {/* Archetype */}
        <div className="p-5 rounded-xl bg-slate-900/60 border border-slate-800/60">
          <div className="flex items-center gap-2 mb-3">
            <Target className="w-4 h-4 text-purple-400" />
            <span className="text-xs text-slate-400 font-medium uppercase tracking-wider">Developer Archetype</span>
          </div>
          <p className="text-xl font-medium text-purple-300 mb-2">{analysis.archetype}</p>
          <p className="text-slate-300">{analysis.summary}</p>
        </div>

        {/* Three Column Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          {/* Primary Domains */}
          <div className="lg:col-span-1">
            <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800/60 h-full">
              <div className="flex items-center gap-2 mb-3">
                <Brain className="w-4 h-4 text-cyan-400" />
                <span className="text-xs text-slate-400 font-medium uppercase tracking-wider">Primary Domains</span>
              </div>
              <div className="flex flex-wrap gap-2">
                {analysis.primaryDomains.map((domain, i) => (
                  <span
                    key={i}
                    className="px-3 py-1.5 bg-cyan-950/50 text-cyan-300 text-xs font-medium rounded-lg border border-cyan-800/60"
                  >
                    {domain}
                  </span>
                ))}
              </div>
            </div>
          </div>

          {/* Signature Innovations */}
          <div className="lg:col-span-1">
            <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800/60 h-full">
              <div className="flex items-center gap-2 mb-3">
                <Lightbulb className="w-4 h-4 text-amber-400" />
                <span className="text-xs text-slate-400 font-medium uppercase tracking-wider">Signature Innovations</span>
              </div>
              <ul className="space-y-2">
                {analysis.signatureInnovations.map((innovation, i) => (
                  <li key={i} className="text-sm text-slate-300 flex items-start gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-amber-500 mt-1.5 flex-shrink-0" />
                    <span>{innovation}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Technical Strengths */}
          <div className="lg:col-span-1">
            <div className="p-4 rounded-xl bg-slate-900/60 border border-slate-800/60 h-full">
              <div className="flex items-center gap-2 mb-3">
                <Award className="w-4 h-4 text-emerald-400" />
                <span className="text-xs text-slate-400 font-medium uppercase tracking-wider">Technical Strengths</span>
              </div>
              <ul className="space-y-2">
                {analysis.technicalStrengths.map((strength, i) => (
                  <li key={i} className="text-sm text-slate-300 flex items-start gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 mt-1.5 flex-shrink-0" />
                    <span>{strength}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>

        {/* Suggested Collaborations */}
        <div className="p-5 rounded-xl bg-slate-900/60 border border-slate-800/60">
          <div className="flex items-center gap-2 mb-3">
            <TrendingUp className="w-4 h-4 text-pink-400" />
            <span className="text-xs text-slate-400 font-medium uppercase tracking-wider">Suggested Collaborations & Next Directions</span>
          </div>
          <p className="text-slate-300">{analysis.suggestedCollaborations}</p>
        </div>
      </div>
    </div>
  );
};